@extends('layouts.app')

@section('title', __('menu.euProjects'))

@section('content')
    <section class="tp-shop-area pb-120">
        <div class="container">
            <div class="row">
                <div class="col-12 mb-4">
                    @include('flash_messages')
                </div>
                <div class="col-12">
                    <div class="tp-shop-main-wrapper">
                        <div class="tp-shop-items-wrapper tp-shop-item-primary">
                            <div class="tab-content" id="productTabContent">
                                <div class="tab-pane fade show active" id="grid-tab-pane" role="tabpanel"
                                    aria-labelledby="grid-tab" tabindex="0">
                                    <div class="row">
                                        <p><img src="{{ asset('images/BFES.jpg') }}" alt="Bendrai finansuoja Europos Sąjunga" class="col-md-6 col-12"></p>
                                        @if (App()->getLocale() == 'lt')
                                            <p>UAB "DTS solutions", įgyvendina projektą <b>"E. pardavimo sandorių sudarymo sprendimų diegimas UAB "DTS Solutions"</b> Nr. 02-033-K-0053. Bendra projekto vertė – <b>50 268,60 Eur</b>, iš kurių <b>24 995,20 Eur</b> sudaro Europos Sąjungos fondų ir (arba) Ekonomikos gaivinimo ir atsparumo didinimo priemonės lėšos ir Lietuvos Respublikos valstybės biudžeto lėšos.</p>
                                            <p>Projektas įgyvendinamas pagal Sutartyje, plėtros programos pažangos priemonės Nr. 05-001-01-05-05 "Skatinti įmones skaitmenizuotis" veiklos "Skatinti labai mažų, mažų ir vidutinių įmonių skaitmeninimą, finansuojant e. pardavimo sandorių sudarymo sprendimų diegimą, paslaugų ir produktų konfigūravimą ir vizualizaciją" poveiklės "Skatinti labai mažų, mažų ir vidutinių įmonių skaitmeninimą, finansuojant e. pardavimo sandorių sudarymo sprendimų diegimą, paslaugų ir produktų konfigūravimą ir vizualizaciją" (Sostinės regionas) ir poveiklės "Skatinti labai mažų, mažų ir vidutinių įmonių skaitmeninimą, finansuojant e. pardavimo sandorių sudarymo sprendimų diegimą, paslaugų ir produktų konfigūravimą ir vizualizaciją" (Vidurio ir vakarų Lietuvos regionas) projektų finansavimo sąlygų apraše, patvirtintame Lietuvos Respublikos ekonomikos ir inovacijų ministro 2022 m. liepos 15 d. įsakymu Nr. 4-877 "Dėl 2022–2030 metų plėtros programos valdytojos Lietuvos respublikos ekonomikos ir inovacijų ministerijos ekonomikos transformacijos ir konkurencingumo plėtros programos pažangos priemonės Nr. 05-001-01-05-05 "Skatinti įmones skaitmenizuotis" aprašo patvirtinimo", Projektų administravimo ir finansavimo taisyklėse patvirtintose Lietuvos Respublikos finansų ministro 2022 m. birželio 22 d. įsakymu Nr. 1K-237 "Dėl 2021–2027 metų Europos Sąjungos fondų investicijų programos ir Ekonomikos gaivinimo ir atsparumo didinimo plano "Naujos kartos Lietuva" įgyvendinimo", ir juose nurodytuose ES ir Lietuvos Respublikos teisės aktuose nustatytas sąlygas ir tvarką.</p>
                                            <p>Projektu siekiama įmonę skaitmenizuotis, įsidiegti e. pardavimo sandorių sudarymo sprendimus UAB "DTS Solutions" – tai informacinių technologijų konsultavimo, informacinių sistemų audito ir programinės įrangos kūrimo paslaugas teikianti įmonė. Vienos labiausiai besiplečiančių įmonės paslaugų - tai įvairių IT paslaugų (toliau – produktų) pardavimas. Iki šiol įmonė savo produktus pardavinėjo tik tiesioginiu būdu, klientų aptarnavimo procesai, įskaitant produktų užsakymų valdymą, nėra skaitmenizuoti, todėl dabartiniai sprendimai nesudaro galimybės darbuotojams teikti paslaugas efektyviai; neturėdama galimybės valdyti verslo sandorių el. būdu (t. y. vykdyti produktų pirkimo ir pardavimo procesą internetu, įskaitant ir produktų paieškos, krepšelio (užsakymo) suformavimo, mokėjimo atlikimo bei užsakymo įvykdymo ir valdymo funkcijas ir pan.), įmonė ribojo potencialių klientų ratą ir tuo pačiu įmonės pajamų augimą.</p>
                                            <p>Įmonė, siekdama padidinti konkurencingumą, pritraukti daugiau klientų ir efektyviau juos aptarnauti, labiau išplėsti pardavimus, nusprendė įsidiegti e. pardavimo sandorių sprendimus ir pardavinėti savo produktus naudojantis elektroninės prekybos sprendimais. Šis projektas inovatyvus tuo, kad bus kuriama e. pardavimo sandorių sudarymo platforma, paremta pažangiausiomis informacinėmis technologijomis, suteikiančias naujas galimybes inovatyviam produktų pardavimui.</p>
                                            <p>Įgyvendintas projektas leis įmonei skaitmenizuoti pardavimų procesą, efektyviau pardavinėti savo produktus, užtikrins greitesnį ir kokybiškesnį klientų aptarnavimą, sutrumpėjęs produktų pardavimo laikas leis aptarnauti daugiau klientų, tai užtikrins didesnį produktų prieinamumą ir įmonės pajamų augimą.</p>
                                            <p>&nbsp;</p>
                                            <p>Projekto veiklas numatyta užbaigti 2025 m. gegužės mėn.
                                            <br>Su projektu susijusios užklausos gali būti adresuojamos <a href="mailto:linas.eidimtas@dts-solutions.lt">linas.eidimtas@dts-solutions.lt</a></p>
                                        @elseif (App()->getLocale() == 'en')
                                            <p>UAB "DTS solutions" is implementing the project <b>"Implementation of e-sales transaction solutions in UAB "DTS Solutions"</b> Nr. 02-033-K-0053. The total value of the project is EUR <b>50,268.60</b>, of which EUR <b>24,995.20</b> is financed by the European Union Funds and/or the Recovery and Resilience Facility and the State Budget of the Republic of Lithuania.</p>
                                            <p>The project is implemented within the framework of the Contract, under the Development Programme Progress Measure No 05-001-01-05-05 "Promote the digitalisation of enterprises", under the activity "Promote the digitalisation of micro, small and medium-sized enterprises by financing the implementation of e-sales transaction solutions, configuration and visualisation of services and products", under the impact of the activity "Promote the digitalisation of micro, small and medium-sized enterprises by financing the digitalisation of e-services and services". The project description of the project "To promote the digitalisation of micro, small and medium-sized enterprises by financing the implementation of e-sales transaction solutions, configuration and visualisation of services and products" (Capital Region) and the project description of the project "To promote the digitalisation of micro, small and medium-sized enterprises by financing the implementation of e-sales transaction solutions, configuration and visualisation of services and products" (Central and Western Region) approved by the Minister of the Republic of Lithuania for Economic Affairs and Innovation in the period from 2022 to 2013 The description of the project financing and the rules for the administration and financing of projects approved by Order No 4-877 of 15 July 2022 "On the approval of the description of the progress measure No 05-001-01-05-05 "Promoting the digitalisation of enterprises" of the Development Programme Manager of the Ministry of Economy and Innovation of the Republic of Lithuania for the period 2022-2030, the rules for the administration and financing of projects approved by the Minister of Finance of the Republic of Lithuania for the period 2022-2030, the rules for the administration and financing of projects approved by the Minister of Finance of the Republic of Lithuania for the period 2022-2030 for the period 2022-2030 for the period 2022-2033, and the description of the project financing and financing of the project financing of the Republic of Lithuania for the period 2022-2033. The conditions and procedures set out in the Regulations of the Minister of Finance of the Republic of Lithuania and the Ministry of Finance of the Republic of Lithuania on the implementation of the European Union Funds Investment Programme for the period 2021-2027 and the Economic Recovery and Resilience Improvement Plan "Lithuania of the New Generation", as well as the conditions and procedures laid down in the legal acts of the European Union and the Republic of Lithuania referred to in these Regulations.</p>
                                            <p>The project aims to digitalize the company and implement e-sales transaction solutions DTS Solutions UAB is a company providing information technology consulting, information systems audit and software development services. One of the company's most expanding services is the sale of various IT services (hereafter: products). Until now, the company has only sold its products directly, its customer service processes, including product order management, have not been digitised, so current solutions do not allow employees to provide services efficiently; the lack of e-business transaction management (i.e. the ability to manage the process of buying and selling products via the internet, including product search, basket (order) creation, payment and order fulfillment and management, etc.), has limited the company's pool of potential customers, and thus limited the company's growth of revenues.</p>
                                            <p>In order to increase its competitiveness, attract and serve more customers more efficiently and expand its sales, the company decided to implement e-sales transaction solutions and sell its products using e-commerce solutions. This project is innovative in that it will develop an e-sales transaction platform based on cutting-edge information technology, providing new opportunities for innovative product sales.</p>
                                            <p>The project will enable the company to digitise its sales process, sell its products more efficiently, provide faster and better customer service, reduce the time needed to sell its products and serve more customers, which will lead to greater product availability and increase the company's revenue.</p>
                                            <p>&nbsp;</p>
                                            <p>The project activities are scheduled to be completed in May 2025.
                                            <br>Inquiries related to the project can be addressed to <a href="mailto:linas.eidimtas@dts-solutions.lt">linas.eidimtas@dts-solutions.lt</a></p>
                                        @else
                                            <p>UAB «DTS Solutions» реализует проект <b>«Внедрение решений по сделкам электронных продаж в UAB «DTS Solutions»</b> Nr. 02-033-K-0053. Общая стоимость проекта составляет <b>50 268,60 евро</b>, из которых <b>24 995,20 евро</b> финансируется за счет средств Европейского Союза и/или Фонда восстановления и устойчивости и государственного бюджета Литовской Республики.</p>
                                            <p>Проект реализуется в рамках Договора, в рамках Меры прогресса Программы развития № 05-001-01-05-05 «Содействие цифровизации предприятий», в рамках мероприятия «Содействие цифровизации микро-, малых и средних предприятий путем финансирования внедрения решений для сделок электронных продаж, конфигурации и визуализации услуг и продуктов», под воздействием мероприятия «Содействие цифровизации микро-, малых и средних предприятий путем финансирования цифровизации электронных услуг и продуктов». Описание проекта «Способствовать оцифровке микро-, малых и средних предприятий путем финансирования внедрения решений для сделок электронной продажи, конфигурирования и визуализации услуг и продуктов» (Столичный регион) и описание проекта «Способствовать оцифровке микро-, малых и средних предприятий путем финансирования внедрения решений для сделок электронной продажи, конфигурирования и визуализации услуг и продуктов» (Центральный и Западный регион), утвержденных министром Литовской Республики по экономическим делам и инновациям в период с 2022 по 2013 гг. Описание финансирования проекта и правила администрирования и финансирования проектов, утвержденные приказом № 4-877 от 15 июля 2022 г. «Об утверждении описания мероприятия прогресса № 05-001-01-05-05 „Содействие цифровизации предприятий“ руководителя программы развития Министерства экономики и инноваций Литовской Республики на период 2022-2030 гг. Условия и процедуры, изложенные в Регламенте Министра финансов Литовской Республики и Министерства финансов Литовской Республики по реализации Инвестиционной программы фондов Европейского Союза на период 2021-2027 гг. и Плана восстановления и повышения устойчивости экономики «Литва нового поколения», а также условия и процедуры, изложенные в правовых актах Европейского Союза и Литовской Республики, упомянутых в настоящем Регламенте.</p> <p>
                                            <p>Проект направлен на цифровизацию компании и внедрение решений для сделок электронных продаж DTS Solutions UAB - компания, предоставляющая услуги по консультированию в области информационных технологий, аудиту информационных систем и разработке программного обеспечения. Одной из наиболее развивающихся услуг компании является продажа различных ИТ-услуг (далее - продукты). До сих пор компания продавала свои продукты только напрямую, процессы обслуживания клиентов, включая управление заказами на продукты, не были оцифрованы, поэтому существующие решения не позволяют сотрудникам эффективно оказывать услуги; отсутствие управления транзакциями электронного бизнеса (т. е. возможности управлять процессом покупки и продажи продуктов через Интернет, включая поиск продуктов, формирование корзины (заказа), оплату, выполнение и управление заказами и т. д.) ограничивало круг потенциальных клиентов компании и, соответственно, рост доходов компании.</p
                                            <p>Для повышения конкурентоспособности, привлечения и более эффективного обслуживания клиентов и расширения продаж компания решила внедрить решения для электронных продаж и продавать свою продукцию с помощью решений для электронной коммерции. Инновационность проекта заключается в том, что в его рамках будет создана платформа электронных продаж, основанная на передовых информационных технологиях и предоставляющая новые возможности для реализации инновационной продукции.</p
                                            <p>Проект позволит компании оцифровать процесс продаж, эффективнее продавать свою продукцию, быстрее и качественнее обслуживать клиентов, сократить время на продажу продукции и обслуживать большее количество клиентов, что приведет к увеличению доступности продукции и росту доходов компании.</p>
                                            <p>&nbsp;</p>
                                            <p>Завершение проекта запланировано на май 2025 года.
                                            <br>По вопросам, связанным с проектом, можно обращаться по адресу <a href=«mailto:linas.eidimtas@dts-solutions.lt»>linas.eidimtas@dts-solutions.lt</a></p>
                                        @endif
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
@endsection
