@extends('layouts.app')

@section('content')
    @include('page_header', [
        'secondPageLink' => 'termsofservice',
        'secondPageName' => __('menu.termsofservice'),
        'hasThirdPage' => false
    ])
    <div class="container product-section my-4">

        @if($lang=="lt")
            <h3 class="mb-4">Prekių pirkimo–pardavimo e-parduotuvės internete taisyklės</h3>

            <p>
            <b>1. Bendrosios nuostatos</b><br>
                1.1. Šios prekių pirkimo – pardavimo taisyklės (toliau – „Taisyklės“) nustato bendrąsias naudojimosi parduotuve internete Krims.lt (toliau – „Krims parduotuvė“) sąlygas. Taisyklės yra taikomos, kai Pirkėjas renkasi, užsako ir perka Krims parduotuvėje siūlomas prekes ar bet kaip kitaip naudojasi Krims parduotuvės teikiamomis paslaugomis.<br>
                1.2. Krims parduotuvė yra viešojo maitinimo parduotuvė internete, orientuota į vartotojus, perkančius Krims gaminamus patiekalus ir (ar) kitus maisto ar su juo susijusius produktus asmeniniams savo ar šeimos poreikiams tenkinti, nesusijusiems su verslu.<br>
                1.3. Krims parduotuvėje prekių prekybą organizuoja, vykdo ir su ja susijusias paslaugas Pirkėjui teikia UAB „Vadeiva“, juridinio asmens kodas 300570003, buveinės adresas: Savanorių pr. 253, LT-02301Vilnius, Lietuvos Respublika, PVM mokėtojo kodas LT100004862117, (toliau – „Pardavėjas“). Krims parduotuvėje parduodamos Pardavėjui nuosavybės teise priklausančios prekės.<br>
                1.4. Pirkėju šiose Taisyklėse yra bet kuris asmuo, perkantis Krims parduotuvėje ar besinaudojantis kitomis Krims parduotuvės paslaugomis (toliau – „Pirkėjas“). Naudotis Krims parduotuve ir joje pirkti turi teisę (a) veiksnūs fiziniai asmenys, t. y. asmenys, sulaukę pilnametystės, kurių veiksnumas nėra apribotas teismo tvarka, ir (b) juridiniai asmenys, veikiantys per įgaliotus atstovus.<br>
                1.5. Užsiregistruodamas arba pateikdamas užsakymą Pirkėjas besąlygiškai patvirtina, jog jis turi teisę pirkti Krims parduotuvėje.<br>
                1.6. Kartu su Pirkėjo pateiktu prekių užsakymu šios Taisyklės tampa tarp Pirkėjo ir Pardavėjo sudaryta sutartimi ir yra abiem šalims privalomas teisinis dokumentas. Sutartis laikoma sudaryta, kai Pirkėjas suformuoja ir pateikia Krims parduotuvėje prekių užsakymą, Taisyklėse nustatyta tvarka ir terminais atlieka apmokėjimą ir Pirkėjo nurodytu elektroniniu paštu Pardavėjas išsiunčia patvirtinimą, kad Pirkėjo užsakymas yra priimtas.<br>
                1.7. Pirkėjui nesuteikiama galimybė pateikti prekių užsakymo Krims parduotuvėje, jeigu jis nėra susipažinęs su Taisyklėmis ir (ar) su jomis nesutinka. Tais atvejais, kai Pirkėjas nesutinka su Taisyklėmis arba tam tikra jų dalimi, jis neturėtų užsakyti prekių Krims parduotuvėje. Pirkėjui užsisakius prekių Krims parduotuvėje laikoma, jog Pirkėjas susipažino ir besąlygiškai sutiko su Taisyklėmis.<br>
                1.8. Pardavėjas pasilieka teisę pakeisti, taisyti ar papildyti Taisykles. Pirkėjui apsiperkant Krims parduotuvėje taikomos Taisyklės, galiojančios užsakymo pateikimo momentu, todėl Pirkėjui rekomenduojama su Taisyklėmis susipažinti kiekvieno apsipirkimo metu.<br>
                1.9. Pardavėjas neprisiima jokios rizikos ar atsakomybės ir yra nuo jos besąlygiškai atleidžiamas, jei Pirkėjas iš dalies ar visiškai nesusipažino su Taisyklėmis, nors jam tokia galimybė buvo suteikta.<br>
                1.10. Pardavėjas turi teisę be įspėjimo apriboti Pirkėjo naudojimąsi Krims parduotuvės paslaugomis, jeigu Pirkėjas Krims parduotuve naudojasi pažeisdamas šias Taisykles, bando pakenkti Krims parduotuvės vykdomų užsakymų, darbo stabilumui ir (arba) saugumui.<br>
                1.11. Pardavėjas gali laikinai arba iš viso nutraukti Krims parduotuvės veiklą, apie tai iš anksto nepranešęs Pirkėjui. Įvykus nenugalimos jėgos (force majeure) aplinkybėms, pardavėjas turi teisę sustabdyti sutarties įvykdymą iki nenugalimos jėgos (force majeure) aplinkybių išnykimo, pranešant Pirkėjui apie užsakymo vykdymo sustabdymą. Jeigu Pirkėjui nebeaktualus vėlesnis sutarties įvykdymas, tuomet pirkėjas turi teisę atsisakyti sutarties apie tai pranešdamas Pardavėjui. Pardavėjui sustabdžius veiklą, bet esant galimybei įvykdyti patvirtintus užsakymus, visos teisės ir pareigos numatytos šiose Taisyklėse ar taikomuose teisės aktuose, susijusios su jau įvykdytais arba vykdomais užsakymais, išlieka galioti.<br>
                <b>2. Užsakymo pateikimas ir asmens duomenų tvarkymas</b><br>
                2.1. Pirkėjas, norėdamas naudotis Krims parduotuve ir pirkti joje siūlomas prekes, privalo Krims parduotuvės sistemoje pateikti šiuos Pirkėjo asmeninius duomenis: vardą, pavardę, elektroninį paštą (kuriuo bus pateikiamas užsakymo patvirtinimas ir su užsakymo atsiėmimu susijusi informacija), telefono numerį, kitus prekių pristatymui būtinus duomenis. Juridinio asmens įgaliotas atstovas vietoje vardo ir pavardės pateikia juridinio asmens pavadinimą.<br>
                2.2. Pirkėjas yra atsakingas, kad pateikti duomenys būtų tikslūs, teisingi ir išsamūs. Pardavėjas jokiu atveju nebus atsakingas už žalą, atsiradusią Pirkėjui ir (ar) tretiesiems asmenims dėl to, jog Pirkėjas nurodė neteisingus ir (ar) neišsamius asmens duomenis. Pateikus (apmokėjus) užsakymą jo atšaukti nebėra galimybės, sumokėti pinigai nėra grąžinami.<br>
                2.3. Pirkėjo asmens duomenys bus tvarkomi pagal Privatumo politiką. Jei Pirkėjas naudojasi Krims parduotuvės paslaugomis, laikoma, kad jis sutinka su Pirkėjo asmens duomenų tvarkymu ir patvirtina, kad visa pateikta informacija ir asmens duomenys yra teisingi ir atitinka tikrovę.<br>
                2.4. Pirkėjo asmens duomenys bus naudojami identifikuojant Pirkėją, nustatant, ar Pirkėjas ir asmuo, kuriam pristatomos prekės, yra pilnametis (Lietuvos Respublikos įstatymų nustatytais atvejais), vykdant prekių pardavimą ir pristatymą, išrašant apskaitos dokumentus, grąžinant permokas ir (ar) pinigus už Pirkėjo grąžintas prekes, administruojant įsiskolinimus, vykdant kitus iš pirkimo-pardavimo sutarties kylančius įsipareigojimus bei užtikrinant Pirkėjui galimybę naudotis kitomis Krims parduotuvės paslaugomis.<br>
                2.5. Pirkėjo asmens duomenys bus tvarkomi tiesioginės rinkodaros tikslais tik gavus Pirkėjo sutikimą. Pirkėjo sutikimas išreiškiamas užpildant registracijos anketą ir šiose Taisyklėse nustatyta tvarka anketoje pažymint atitinkamus laukus.<br>
                <b>3. Prekių kainos, apmokėjimo tvarka ir terminai</b><br>
                3.1. Prekių kainos Krims parduotuvėje ir suformuotame užsakyme nurodomos Eurais su PVM. Prekės Pirkėjui parduodamos kainomis, galiojančiomis Krims parduotuvėje užsakymo pateikimo momentu.<br>
                3.2. Pirkėjas atsiskaito už prekes apmokėjimas naudojantis partnerio paslaugomis. Klientas Krims parduotuvės sistemoje nepalieka mokėjimo duomenų, kadangi mokėjimo operacijos atlikimui Pirkėjas nukreipiamas į sertifikuoto paslaugos teikėjo saugų serverį. Iš šio serverio Krims parduotuvės sistemai yra grąžinama tik dalinė informacija apie apmokėjimo būseną.<br>
                3.3. Pirkėjas už užsakytas prekes įsipareigoja sumokėti nedelsiant. Tik Pardavėjui iš jo pasirinkto mokėjimų sistemos operatoriaus gavus atitinkamą Pirkėjo mokėjimo už prekes bei jų pristatymą (transportavimą) atlikimo patvirtinimą pradedamas vykdyti užsakymas.<br>
                3.4. Užsakymo atsiėmimo laiką Pirkėjas gali pasirinkti iš Krims parduotuvėje pateikiamų apytikslių laikų.<br>
                3.5. PVM sąskaitą-faktūrą Pardavėjas išrašo ir Pirkėjui pateikia Pirkėjo Registracijos anketoje nurodytu elektroniniu paštu iš karto po užsakymo apmokėjimo.<br>
                <b>4. Prekių komplektavimas ir atsiėmimas</b><br>
                4.1. Užsakytas prekes Pirkėjas atsiima užsakymo metu pasirinktame Krims greito maisto restorane. Pirkėjui padarius klaidą ir prekes užsakius kitame restorane, Pardavėjas neturi galimybės perkelti užsakymo į kitą restoraną, ar jo atšaukti.<br>
                4.2. Pirkėjas prekes užsako bei atsiima pasirinktame Krims greito maisto restorane jo užsakymo formavimo metu pasirinktu laiku. Esant dideliam užsakymų skaičiui, Pardavėjas savo nuožiūra gali protingumo ribose prailginti pasiėmimo laiką. Pagamintas maistas yra saugomas 2 valandas nuo jo pagaminimo. Po 2 valandų maistas privalo būti utilizuojamas.<br>
                4.3. Esant pageidavimui, už prekių pakavimo paslaugą į popierinius maišelius išsinešimui yra taikomas vienkartinis fiksuotas pakavimo mokestis.<br>
                4.4. Jei Pirkėjas gavo ne visas jo užsakytas prekes, jo pasirinkimu jis gali trūkstamas prekes atsiimti bet kurioje Krims prekybos vietoje arba Pinigai už Pirkėjo apmokėtas, tačiau Pardavėjo nepateiktas prekes, sumokami į Pirkėjo sąskaitą per 5 (penkias) darbo dienas,  Lietuvos Respublikoje nustatytos ekstremalios padėties metu pinigų grąžinimas gali užtrukti iki 14 (keturiolikos) darbo dienų.<br>
                4.5. Tais atvejais, kai prekių priėmimo metu Pirkėjas pastebi, jog pakuotėje nėra tinkamo prekių kiekio arba pateiktos prekės neatitinka jo užsakytų prekių ir tai nėra nurodyta sąskaitoje-faktūroje, prekių lydraštyje ar kitame prekių perdavimo – priėmimo dokumente, Pirkėjas privalo nedelsiant (prekių atsiėmimo metu) informuoti apie tai Pardavėją.<br>
                <b>5. Prekių kokybės garantija ir tinkamumo naudoti terminas</b><br>
                5.1. Pardavėjas neatsako už tai, kad Krims parduotuvėje internete esančios prekės savo spalva, forma ar kitais parametrais gali neatitikti realaus prekių dydžio, formų ir spalvos dėl Pirkėjo naudojamo vaizduoklio (monitoriaus) ypatybių ar kitų techninių priežasčių, taip pat atsižvelgiant į protingai galimus išvaizdos neatitikimus. Krims parduotuvėje internete pateikiamos patiekalų nuotraukos yra iliustracinio pobūdžio ir protingumo ribose gali skirtis nuo realiai pagaminto patiekalo.<br>
                5.2. Pardavėjas patvirtina, kad yra atsakingas už Krims internetinėje parduotuvėje užsakytų prekių pardavimą ir įsigytų prekių tinkamą pristatymą, prekių kokybę, bei kitų teisės aktuose numatytų Pardavėjo teisių ir pareigų įgyvendinimą.<br>
                5.3. Tuo atveju, kai Pardavėjas tam tikroms prekių rūšims daiktų kokybės garantijos nesuteikia, galioja garantija, numatyta atitinkamų teisės aktų.<br>
                <b>6. Pretenzijų dėl prekių pateikimas</b><br>
                6.1. Jei Pirkėjas nėra patenkintas pateiktų greitai gendančių prekių kokybe, o tokiomis prekėmis laikomi maisto produktai ir gėrimai, kurių galiojimo terminas yra trumpas, įskaitant ir tuos produktus, kurie turi būti laikomi šaldytuve pagal gamintojo nustatytą temperatūrinį rėžimą, į Pardavėją privalo kreiptis ne vėliau, kaip per 48 valandas nuo prekių pristatymo tinklalapyje www.krims.lt, “Atsiliepimų” skiltyje. Pirkėjas pateikdamas pretenziją, dėl nekokybiškų prekių, kartu privalo pateikti ir gautos nekokybiškos prekės nuotrauką, užsakymo numerį ir apmokėjimą įrodančius dokumentus (el. paštu gautą sąskaitą - faktūrą).<br>
                6.2. Jei Pirkėjas kreipiasi vėliau nei nurodytas terminas ir/ar nepateikia prekės nuotraukos, Pardavėjas neįsipareigoja Pirkėjo skundo spręsti Pirkėjo naudai.<br>
                <b>7. Baigiamosios nuostatos</b><br>
                7.1. Šios Taisyklės sudarytos vadovaujantis Lietuvos Respublikos teisės aktais.<br>
                7.2. Šių Taisyklių pagrindu kylantiems santykiams taikoma Lietuvos Respublikos teisė.<br>
                7.3. Atsiradus žalai, kaltoji šalis atlygina kitai šaliai tiesioginius nuostolius Lietuvos Respublikos įstatymų nustatyta tvarka ir pagrindais.<br>
                7.4. Visi nesutarimai, kilę dėl šių Taisyklių vykdymo, sprendžiami derybų būdu. Nepavykus susitarti, ginčai sprendžiami Lietuvos Respublikos įstatymų nustatyta tvarka.<br>
                7.5. Kiekvienas vartotojas turi galimybę spręsti su Padavėju iškilusius ginčus ir elektroniniu būdu, nesikreipdamas į teismą. Pirmiausia vartotojas raštu turi kreiptis į Pardavėją bei per 14 dienų nuo pretenzijos gavimo, Pardavėjui neatsakius į vartotojo pretenziją, arba nepatenkinus vartotojo pretenzijos, vartotojas gali kreiptis į ne teismo tvarka vartojimo ginčus nagrinėjantį subjektą, t.y. Valstybinę vartotojų teisių apsaugos tarnybą (Vilniaus g.25, 01402 Vilnius, el. p. <a href="mailto:tarnyba@vvtat.lt">tarnyba@vvtat.lt</a>, tel. 852626751, interneto svetainė <a href="https://www.vvtat.lt/" target="_blank">www.vvtat.lt</a>), arba į jos teritorinius padalinius apskrityse ar užpildyti prašymo formą EGS platformoje <a href="http://ec.europa.eu/ods/" target="_blanks">http://ec.europa.eu/ods/</a>).
            </p>
        @elseif ($lang == "ru")
            <h3 class="mb-4">Правила покупки и продажи товаров в онлайн-магазине</h3>

            <p>
                <b>1. Общие положения</b><br>
                1.1. Настоящие Правила и условия продажи и покупки товаров (далее "Правила и условия") устанавливают общие условия пользования интернет-магазином Krims.lt (далее "Магазин Krims"). Правила применяются, когда Клиент выбирает, заказывает и приобретает товары, предлагаемые в Магазине Krims, или иным образом пользуется услугами, предоставляемыми Магазином Krims.<br>
                1.2. Магазин Krims - это интернет-магазин общественного питания, предназначенный для потребителей, которые приобретают блюда и/или другие продукты питания или сопутствующие товары, произведенные компанией Krims, для своих личных, не связанных с бизнесом, нужд или нужд своей семьи.
                1.3. Продажу товаров в магазине Krims организует, проводит и предоставляет Покупателю сопутствующие услуги ЗАО "Vadeiva", код юридического лица 300570003, юридический адрес: пр. Саванорю 253, LT-02301Вильнюс, Литовская Республика, код налогоплательщика НДС LT100004862117, (далее "Продавец"). В магазине Krims продаются товары, принадлежащие Продавцу.<br>
                1.4. Для целей настоящих Положений и условий Клиентом является любое лицо, которое совершает покупки в Магазине Krims или пользуется другими услугами Магазина Krims (далее "Клиент"). Право пользования и покупки в Магазине Krims имеют (а) дееспособные физические лица, т.е. лица, достигшие совершеннолетия и чья дееспособность не была ограничена судом, и (б) юридические лица, действующие через уполномоченных представителей.
                1.5. Регистрируясь или размещая заказ, Покупатель безоговорочно подтверждает, что он/она имеет право совершать покупки в Магазине Krims.<br>.
                1.6. Вместе с заказом Покупателя настоящие Условия становятся договором между Покупателем и Продавцом и представляют собой обязательный юридический документ для обеих сторон. Договор считается заключенным, когда Покупатель сформирует и отправит заказ в магазине Krims, произведет оплату в порядке и в сроки, установленные Условиями, а Продавец отправит подтверждение о принятии заказа Покупателя на указанный Покупателем адрес электронной почты.
                1.7. Покупателю не предоставляется возможность разместить заказ на товары в Магазине Krims, если он не ознакомлен с Положениями и Условиями и/или не согласен с ними. В случаях, когда Покупатель не согласен с Положениями и условиями или любой их частью, Покупатель не должен размещать заказ в Магазине Krims. Если Клиент заказывает товары в Магазине Krims, считается, что Клиент прочитал и безоговорочно принял Положения и Условия.<br>.
                1.8. Продавец оставляет за собой право изменять, дополнять или изменять Положения и условия. Положения и условия, действующие на момент размещения заказа, применяются к покупкам Покупателя в Магазине Krims, поэтому Покупателю рекомендуется ознакомиться с Положениями и условиями во время каждой покупки.
                1.9. Продавец не принимает на себя никакого риска или ответственности и безоговорочно освобождается от любого такого риска или ответственности в случае, если Покупатель полностью или частично не прочитает Условия, несмотря на то, что ему была предоставлена такая возможность.<br>
                1.10. Продавец имеет право ограничить использование Покупателем Магазина Krims без уведомления, если Покупатель использует Магазин Krims в нарушение настоящих Условий, пытается вмешаться в стабильность и/или безопасность заказа, работы и/или безопасности Магазина Krims.
                1.11. Продавец может временно или постоянно прекратить работу Магазина Krims без предварительного уведомления Покупателя. В случае форс-мажорных обстоятельств Продавец имеет право приостановить исполнение договора до прекращения форс-мажорных обстоятельств, уведомив Покупателя о приостановке заказа. Если Покупатель больше не заинтересован в последующем исполнении Договора, то он имеет право отказаться от Договора, уведомив об этом Продавца. В случае приостановления Продавцом своей деятельности, но возможности выполнения подтвержденных заказов, все права и обязанности, предусмотренные настоящими Условиями или действующим законодательством в отношении уже выполненных или находящихся в процессе выполнения заказов, остаются в силе.<br>.
                <b>2. Размещение заказа и обработка персональных данных</b><br>
                2.1. Для того чтобы воспользоваться Магазином Krims и приобрести предлагаемые в нем товары, Покупатель должен предоставить следующие личные данные Покупателя в системе Магазина Krims: имя, фамилию, адрес электронной почты (который будет использоваться для подтверждения заказа и информации, связанной со сбором заказа), номер телефона, другие данные, необходимые для доставки товара. Уполномоченный представитель юридического лица вместо имени и фамилии указывает наименование юридического лица.<br>
                2.2. Покупатель несет ответственность за то, чтобы предоставленные данные были точными, правильными и полными. Продавец ни при каких обстоятельствах не несет ответственности за ущерб, причиненный Покупателю и/или третьим лицам вследствие предоставления Покупателем неверных и/или неполных персональных данных. После размещения (оплаты) заказа, он не может быть отменен и возврат средств не производится.<br>
                2.3. Персональные данные Покупателя будут обрабатываться в соответствии с Политикой конфиденциальности. Если Покупатель пользуется услугами Магазина Krims, считается, что Покупатель дал согласие на обработку персональных данных Покупателя и подтвердил, что вся предоставленная информация и персональные данные являются верными и правильными.
                2.4. Личные данные Покупателя используются для идентификации Покупателя, определения совершеннолетия Покупателя и лица, которому доставляется товар (в случаях, предусмотренных законодательством Литовской Республики), осуществления продажи и доставки товара, выдачи бухгалтерских документов, возврата переплат и/или возврата денег за возвращенный товар, урегулирования любых задолженностей, выполнения других обязательств, вытекающих из договора купли-продажи, и обеспечения возможности доступа Покупателя к другим услугам, предоставляемым магазином Krim.
                2.5. Персональные данные Покупателя будут обрабатываться в целях прямого маркетинга только с согласия Покупателя. Согласие Покупателя выражается путем заполнения регистрационной формы и проставления галочек в соответствующих графах формы в порядке, установленном настоящими Условиями.
                <b>3. Цены, порядок и условия оплаты</b><br>.
                3.1. Цены на товары в магазине Krims и в бланке заказа указываются в евро с учетом НДС. Товары продаются Покупателю по ценам, действующим в магазине Krims на момент размещения заказа.<br>.
                3.2. Покупатель оплачивает Товары, пользуясь услугами Партнера. Клиент не оставляет платежные реквизиты в системе Krims Shop, так как для проведения платежной операции Клиент перенаправляется на защищенный сервер сертифицированного поставщика услуг. С этого сервера в систему Krims Shop возвращается лишь частичная информация о статусе платежа.<br>
                3.3. Покупатель обязуется немедленно оплатить заказанный товар. Только после получения Продавцом от выбранного им оператора платежной системы соответствующего подтверждения оплаты Покупателем товара и его доставки/транспортировки, начинается исполнение заказа.<br>
                3.4. Покупатель может выбрать время получения заказа из приблизительного времени, доступного в магазине Krims.<br>.
                3.5. Счет-фактураНДС выписывается Продавцом и предоставляется Покупателю по адресу электронной почты Покупателя, указанному в Регистрационной форме Покупателя, сразу после оплаты заказа.<br>.
                <b>4. Подбор и сбор товаров</b><br>
                4.1. Клиент обязан забрать заказанные товары из выбранного им/ею ресторана быстрого питания Krims в момент заказа. Если Покупатель ошибется и закажет товар в другом ресторане, Продавец не сможет перенести заказ в другой ресторан или отменить заказ.<br>
                4.2. Клиент должен заказать и забрать Товары из выбранного им ресторана быстрого питания Krims в выбранное при оформлении заказа время. В случае большого количества заказов Продавец может по своему усмотрению продлить время забора в разумных пределах. Пища хранится в течение 2 часов после ее изготовления. Через 2 часа пища должна быть утилизирована.<br>
                4.3. По желанию клиента за услугу упаковки товаров в бумажные пакеты на вынос взимается единовременная фиксированная плата за упаковку.<br>
                4.4. Если Покупатель получил не все заказанные им товары, он может по своему выбору забрать недостающие товары в любой торговой точке Krims или деньги за товары, оплаченные Покупателем, но не доставленные Продавцом, будут перечислены на счет Покупателя в течение 5 (пяти) рабочих дней, во время чрезвычайного положения в Литовской Республике возврат денег может занять до 14 (четырнадцати) рабочих дней.
                4.5. В случаях, когда Покупатель во время приемки товара замечает, что упаковка не содержит правильного количества товара или поставленный товар не соответствует товару, заказанному Покупателем, и это не указано в счете-фактуре, сопроводительной накладной или любом другом документе о передаче и приемке товара, Покупатель должен немедленно (во время получения товара) сообщить об этом Продавцу.
                <b>5. Гарантия качества товара и срока годности</b><br>.
                5.1. Продавец не несет ответственности за то, что цвет, форма или другие параметры товара в интернет-магазине Krims могут не соответствовать реальным размерам, форме и цвету товара из-за характеристик дисплея (монитора), используемого Клиентом, или по любым другим техническим причинам, а также с учетом обоснованно возможных расхождений во внешнем виде. Фотографии блюд в интернет-магазине Krims предназначены исключительно для иллюстрации и могут в разумных пределах отличаться от реального блюда.<br>
                5.2. Продавец подтверждает, что он несет ответственность за продажу товаров, заказанных в интернет-магазине Krims, а также за надлежащую доставку приобретенных товаров, качество товаров и осуществление других прав и обязанностей Продавца в соответствии с законодательством.<br>
                5.3. В случае, если Продавец не гарантирует качество определенных видов товаров, применяется гарантия, предусмотренная соответствующим законодательством.<br>
                <b>6. Подача жалоб на товар</b><br>
                6.1. Если Покупатель не удовлетворен качеством доставленного скоропортящегося товара, и такой товар относится к продуктам питания и напиткам с коротким сроком хранения, включая те продукты, которые должны быть охлаждены в соответствии с температурным режимом производителя, Покупатель должен связаться с Продавцом не позднее 48 часов с момента доставки товара на сайте www.krims.lt, в разделе "Обратная связь". При подаче претензии по поводу бракованного товара Покупатель должен также предоставить фотографию полученного бракованного товара, номер заказа и подтверждение оплаты (счет, полученный по электронной почте)<br>.
                6.2. Если Покупатель обратится позже указанного срока и/или не предоставит фотографию товара, Продавец не обязан разрешать претензию Покупателя в пользу Покупателя.<br>
                <b>7. Заключительные положения</b><br>
                7.1. Настоящие Условия составлены в соответствии с законодательством Литовской Республики.<br>
                7.2. К отношениям, возникающим в соответствии с настоящими Условиями, применяется право Литовской Республики.<br>
                7.3. В случае причинения ущерба виновная сторона возмещает другой стороне прямой ущерб в порядке и на основаниях, установленных законами Литовской Республики.<br>.
                7.4. Все споры, возникающие в связи с применением настоящих Положений и условий, разрешаются путем переговоров. В случае недостижения соглашения споры разрешаются в порядке, установленном законодательством Литовской Республики.<br>
                7.5. Каждый Пользователь имеет возможность разрешать любые споры с Провайдером в электронном виде, не обращаясь в суд. Потребитель должен сначала обратиться к продавцу в письменной форме и в течение 14 дней с момента получения претензии, если продавец не ответит на претензию потребителя или не удовлетворит его требования, потребитель может обратиться во внесудебный орган по рассмотрению потребительских споров, т.е. в Государственную службу защиты прав потребителей (Vilniaus g.25, 01402 Vilnius, e-mail <a href="mailto:tarnyba@vvtat.lt">tarnyba@vvtat.lt</a>, тел. 852626751, веб-сайт <a href="https://www.vvtat.lt/" target="_blank">www.vvtat.lt</a>), или в его территориальные подразделения в уездах, или заполнив форму заявки на платформе EGS <a href="http://ec.europa.eu/ods/" target="_blank">http://ec.europa.eu/ods/</a>).
            </p>

        @else
            <h3 class="mb-4">Rules for buying and selling goods in an online e-shop</h3>

            <p>
                <b>1. General provisions</b><br>
                1.1. These Terms and Conditions of Sale and Purchase of Goods (hereinafter referred to as the "Terms and Conditions") set out the general terms and conditions for the use of the Krims.lt online shop (hereinafter referred to as the "Krims Shop"). The Rules shall apply when the Customer selects, orders and purchases goods offered in the Krims Shop or otherwise uses the services provided by the Krims Shop.<br>
                1.2. the Krims Shop is an online catering shop aimed at consumers who purchase meals and/or other food or related products produced by Krims for their own or their family's personal, non-business-related needs.
                1.3.The sale of goods in the Krims shop is organised, conducted and related services are provided to the Buyer by UAB "Vadeiva", legal entity code 300570003, registered office address: 253 Savanorių pr., LT-02301Vilnius, Republic of Lithuania, VAT payer code LT100004862117, (hereinafter referred to as the "Vendor"). The Krims shop sells goods owned by the Seller.<br>
                1.4. For the purposes of these Terms and Conditions, a Customer is any person who purchases from the Krims Shop or uses other services of the Krims Shop (hereinafter referred to as "Customer"). The right to use and purchase from the Krims Shop shall be vested in (a) natural persons of legal capacity, i.e. persons who have reached the age of majority and whose legal capacity has not been restricted by a court of law, and (b) legal persons acting through authorised representatives.
                1.5. By registering or placing an order, the Customer unconditionally confirms that he/she has the right to make purchases in the Krims Shop.<br>
                1.6. Together with the Buyer's order, these Terms and Conditions shall become a contract between the Buyer and the Seller and shall constitute a binding legal document for both parties. The contract shall be deemed to have been concluded when the Buyer forms and submits an order in the Krims Shop, makes payment in accordance with the procedure and within the time limits set out in the Terms and Conditions, and the Seller sends a confirmation of the acceptance of the Buyer's order to the e-mail address indicated by the Buyer.
                1.7. The Buyer shall not be given the opportunity to place an order for goods in the Krims Shop if he/she is not familiar with the Terms and Conditions and/or does not agree with them. In cases where the Buyer does not agree with the Terms and Conditions or any part thereof, the Buyer should not place an order in the Krims Shop. If the Customer orders goods in the Krims Shop, the Customer shall be deemed to have read and unconditionally accepted the Terms and Conditions.<br>
                1.8. The Seller reserves the right to change, amend or supplement the Terms and Conditions. The Terms and Conditions in force at the time of placing an order shall apply to the Buyer's purchases in the Krims Shop, and the Buyer is therefore advised to familiarise himself with the Terms and Conditions at the time of each purchase.
                1.9. The Seller accepts no risk or liability and is unconditionally relieved of any such risk or liability in the event that the Buyer fails to read the Terms and Conditions in whole or in part, despite having been given the opportunity to do so.<br>
                1.10. The Seller shall have the right to restrict the Buyer's use of the Krims Shop without notice if the Buyer uses the Krims Shop in violation of these Terms and Conditions, attempts to interfere with the stability and/or security of the Krims Shop's ordering, operation and/or security.
                1.11. The Seller may temporarily or permanently discontinue the operation of the Krims Shop without prior notice to the Buyer. In the event of force majeure, the Seller shall be entitled to suspend the performance of the contract until the force majeure has ceased by notifying the Buyer of the suspension of the order. If the Buyer is no longer interested in the subsequent performance of the Contract, then the Buyer has the right to withdraw from the Contract by notifying the Seller. In the event of the Seller's suspension of its activities, but the possibility of fulfilling confirmed orders, all rights and obligations provided for in these Terms and Conditions or in the applicable legislation in relation to orders already fulfilled or in progress shall remain in force.<br>
                <b>2. Placing an order and processing personal data</b><br>
                2.1. In order to use the Krims Shop and purchase the goods offered therein, the Buyer must provide the following personal data of the Buyer in the Krims Shop system: name, surname, e-mail address (which will be used for order confirmation and information related to the collection of the order), telephone number, other data necessary for the delivery of goods. The authorised representative of a legal entity shall provide the name of the legal entity instead of the name and surname.<br>
                2.2. It is the responsibility of the Buyer to ensure that the data provided is accurate, correct and complete. In no event shall the Seller be liable for damages caused to the Buyer and/or third parties due to the Buyer's provision of incorrect and/or incomplete personal data. Once an order has been placed (paid for), it cannot be cancelled and no refund will be given.<br>
                2.3. The Buyer's personal data will be processed in accordance with the Privacy Policy. If the Buyer uses the services of the Krims Shop, the Buyer shall be deemed to have consented to the processing of the Buyer's personal data and to have confirmed that all information and personal data provided is true and correct.
                2.4. The Buyer's personal data will be used to identify the Buyer, to determine whether the Buyer and the person to whom the goods are being delivered are of legal age (in the cases provided for by the laws of the Republic of Lithuania), to carry out the sale and delivery of the goods, to issue accounting documents, to refund any overpayments and/or refunds for the returned goods, to administer any arrears, to perform other obligations arising from the sale and purchase agreement, and to ensure the Buyer's ability to access the other services provided by the Krim shop.
                2.5. The Buyer's personal data will only be processed for direct marketing purposes with the Buyer's consent. The Buyer's consent shall be expressed by completing the registration form and by ticking the appropriate boxes in the form in accordance with the procedure set out in these Terms and Conditions.
                <b>3. Prices, payment arrangements and terms</b><br>
                3.1. The prices of the goods in the Krims Shop and in the order form are quoted in Euros including VAT. The goods shall be sold to the Buyer at the prices in force in the Krims shop at the time of placing the order.<br>
                3.2. The Buyer shall pay for the Goods using the services of the Partner. The Customer does not leave payment details in the Krims Shop system, as the Customer is redirected to a secure server of a certified service provider for the payment transaction. From this server, only partial information about the status of the payment is returned to the Krims Shop system.<br>
                3.3. The Buyer undertakes to pay for the ordered goods immediately. Only after the Seller has received from the payment system operator of its choice the appropriate confirmation of the Buyer's payment for the goods and their delivery/transportation, shall the execution of the order commence.<br>
                3.4. The Buyer may choose the time of order pick-up from the approximate times available in the Krims Shop.<br>
                3.5. The VAT invoice shall be issued by the Seller and provided to the Buyer by the Buyer's e-mail address specified in the Buyer's Registration Form immediately after the payment of the order.<br>
                <b>4. Pick-up and collection of goods</b><br>
                4.1. The Customer shall collect the ordered goods from the Krims fast food restaurant of his/her choice at the time of order. If the Buyer makes a mistake and orders the goods at another restaurant, the Seller shall not be able to transfer the order to another restaurant or cancel the order.<br>
                4.2. The Customer shall order and collect the Goods from the Krims fast food restaurant of his choice at the time selected at the time of placing his order. In the event of a large number of orders, the Seller may, at its sole discretion, extend the pick-up time within reasonable limits. The food is stored for 2 hours after it has been produced. After 2 hours, the food must be disposed of.<br>
                4.3. If requested, a one-off fixed packing fee applies for the service of packing goods in paper takeaway bags.<br>
                4.4. If the Buyer has not received all of the goods ordered by him/her, he/she may, at his/her option, collect the missing goods at any Krims outlet or the money for the goods paid for by the Buyer, but not delivered by the Seller, shall be paid to the Buyer's account within 5 (five) working days, during the state of emergency in the Republic of Lithuania the refund of the money may take up to 14 (fourteen) working days.
                4.5. In cases where the Buyer notices at the time of acceptance of the goods that the packaging does not contain the correct quantity of goods or the goods delivered do not correspond to the goods ordered by the Buyer, and this is not stated in the invoice, the accompanying delivery note or any other handover and acceptance document, the Buyer must immediately (at the time of collection of the goods) inform the Seller of this fact.
                <b>5. Guarantee of the quality of the goods and the period of fitness for use</b><br>
                5.1. The Seller shall not be liable for the fact that the colour, shape or other parameters of the goods in the Krims online shop may not correspond to the actual size, shape and colour of the goods due to the characteristics of the display (monitor) used by the Customer or for any other technical reasons, as well as taking into account the reasonably possible discrepancies in appearance. The photographs of the dishes in the Krims online shop are for illustrative purposes only and may, within reasonable limits, differ from the actual dish.<br>
                5.2. The Seller confirms that it is responsible for the sale of the goods ordered in the Krims online shop and for the proper delivery of the purchased goods, the quality of the goods, and the exercise of the Seller's other rights and obligations under the law.<br>
                5.3. In the event that the Seller does not guarantee the quality of certain types of goods, the warranty provided for in the relevant legislation shall apply.<br>
                <b>6. Lodging complaints about the goods</b><br>
                6.1. If the Buyer is not satisfied with the quality of the perishable goods delivered, and such goods are considered to be food and beverages with a short shelf life, including those products that must be refrigerated in accordance with the manufacturer's temperature regime, the Buyer must contact the Seller no later than within 48 hours of the date of delivery of the goods on the website www.krims.lt, in the "Feedback" section. When submitting a complaint regarding faulty goods, the Buyer must also submit a photo of the faulty goods received, the order number and proof of payment (invoice received by e-mail).<br>
                6.2. If the Buyer applies later than the specified time limit and/or fails to provide a photograph of the item, the Seller shall not be obliged to resolve the Buyer's complaint in the Buyer's favour.<br>
                <b>7. Final provisions</b><br>
                7.1. These Terms and Conditions are made in accordance with the legislation of the Republic of Lithuania.<br>
                7.2. The law of the Republic of Lithuania shall apply to relations arising under these Terms and Conditions.<br>
                7.3. In the event of damage, the guilty party shall indemnify the other party for direct losses in accordance with the procedure and on the grounds established by the laws of the Republic of Lithuania.
                7.4. All disputes arising out of the application of these Terms and Conditions shall be settled by negotiation. In the event of failure to reach an agreement, disputes shall be settled in accordance with the procedure established by the laws of the Republic of Lithuania.<br>
                7.5. Each User shall have the possibility to settle disputes with the Sender electronically without going to court. The Consumer shall first contact the Seller in writing and within 14 days from the receipt of the claim, if the Seller fails to respond to the Consumer's claim or fails to satisfy the Consumer's claim, the Consumer may apply to the out-of-court consumer disputes body, i.e., the State Consumer Rights Protection Service (Vilniaus g.25, 01402 Vilnius, email <a href="mailto:tarnyba@vvtat.lt">tarnyba@vvtat.lt</a>, tel. 852626751, website <a href="https://www.vvtat.lt/" target="_blank">www.vvtat.lt</a>), or to its territorial units in the counties or by filling in the application form on the EGS platform <a href="http://ec.europa.eu/ods/" target="_blank">http://ec.europa.eu/ods/</a>.)
            </p>

        @endif

    </div>
@endsection
